base:INFO:Executing: 1981-01-01 00:00:00 to 1981-12-31 00:00:00
base:INFO:Runtime: 364 days
base:INFO:Timestep (dt): 240 minutes
base:INFO:Output (dt): 1 days
base:INFO:Repeat release: 6 days
base:INFO:Depths: 14 dz=25 [25 to 350]
base:INFO:Latitudes: 14 dy=0.4 [-2.6 to 2.6]
base:INFO:Longitudes: 1 [190]
base:INFO:Particles (/repeatdt): 196
base:INFO:Particles (total): 11760
base:INFO:Time decorator used.
base:INFO:Fieldset import method= netcdf.
base:INFO:Field import=netcdf, Chunks=False
WARNING: Casting lon data to np.float32
WARNING: Casting lat data to np.float32
WARNING: Casting depth data to np.float32
WARNING: Trying to initialize a shared grid with different chunking sizes - action prohibited. Replacing requested field_chunksize with grid's master chunksize.
base:INFO:ofam_fieldset: 0:0:13.76 total: 13.76 seconds.
base:INFO:ParticleFile_1981-1981_v1i: Started.
WARNING: Particle initialisation from field can be very slow as it is computed in scipy mode.
base:INFO:EUC_pset: 0:1:46.86 total: 106.86 seconds.
base:DEBUG:Particles removed: 93
base:INFO:remove_westward_particles: 0:0:00.03 total: 0.03 seconds.
base:DEBUG:ParticleFile_1981-1981_v1i: Output file.
base:INFO:ParticleFile_1981-1981_v1i:pset.Kernel(Age) + AdvectionRK4_3D
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 127, in <module>
    add_transport=args.transport, write_fieldset=args.fieldset)
  File "/g/data/e14/as3189/OFAM/scripts/tools.py", line 121, in timed
    result = method(*args, **kw)
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 79, in run_EUC
    remove_westward=True)
  File "/g/data/e14/as3189/OFAM/scripts/tools.py", line 121, in timed
    result = method(*args, **kw)
  File "/g/data/e14/as3189/OFAM/scripts/main.py", line 267, in EUC_particles
    kernels = (pset.Kernel(Age) + AdvectionRK4_3D)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/site-packages/parcels/particleset.py", line 764, in Kernel
    delete_cfiles=delete_cfiles)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/site-packages/parcels/kernel.py", line 135, in __init__
    self.funcvars)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/site-packages/parcels/codegenerator.py", line 391, in generate
    self.visit(py_ast)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/site-packages/parcels/codegenerator.py", line 422, in visit_FunctionDef
    self.visit(stmt)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/site-packages/parcels/codegenerator.py", line 836, in visit_Return
    self.visit(node.value)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/ast.py", line 275, in generic_visit
    for field, value in iter_fields(node):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/ast.py", line 186, in iter_fields
    for field in node._fields:
AttributeError: 'NoneType' object has no attribute '_fields'
